name: Christina M Harris
favicon: null
layout_spectrum: 0.9660345793236047
typography_spectrum: 0.10891
title: Website of Author Christina M. Harris
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#84695a'
    - '#c69d94'
    - '#513a2b'
    - '#070100'
    - '#fdfdfb'
  brandStrength: 0.4261912158690393
  lightness: 0.6633685070555657
  saturation: 0.7069872603751719
  rhythmicContrast: 0.9305147179402411
purpose: []
