name: ChristinaMHarris
favicon: null
layout_spectrum: 0.9660345793236047
typography_spectrum: 0.4058547201566398
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4261912158690393
  lightness: 0.6633685070555657
  saturation: 0.7069872603751719
  rhythmicContrast: 0.9305147179402411
purpose: []
